-- Lab 37 steps 5-9 — CRM schema. Run as crm_app:
--   psql -f database/02_schema.sql
-- Full-path types: NUMERIC(19,2) money, TIMESTAMPTZ audit columns, four
-- statuses including SUSPENDED. Do not mix with the timed-path contract.

\set ON_ERROR_STOP on
SET search_path = crm_app;

-- Step 5 — CUSTOMER
CREATE TABLE customer (
  customer_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  public_id        VARCHAR(36) NOT NULL,
  full_name        VARCHAR(150) NOT NULL,
  email_normalized VARCHAR(254) NOT NULL,
  phone            VARCHAR(30),
  status           VARCHAR(20) DEFAULT 'PROSPECT' NOT NULL,
  version_no       INTEGER DEFAULT 0 NOT NULL,
  created_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_customer PRIMARY KEY (customer_id),
  CONSTRAINT uk_customer_public UNIQUE (public_id),
  CONSTRAINT uk_customer_email UNIQUE (email_normalized),
  CONSTRAINT ck_customer_status CHECK (
    status IN ('PROSPECT', 'ACTIVE', 'SUSPENDED', 'CLOSED')
  ),
  CONSTRAINT ck_customer_email_lower CHECK (email_normalized = lower(email_normalized))
);

-- Step 6 — ACCOUNT
CREATE TABLE account (
  account_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_number VARCHAR(34) NOT NULL,
  customer_id    BIGINT NOT NULL,
  account_type   VARCHAR(20) NOT NULL,
  status         VARCHAR(20) DEFAULT 'OPEN' NOT NULL,
  balance        NUMERIC(19, 2) DEFAULT 0 NOT NULL,
  currency       CHAR(3) DEFAULT 'CAD' NOT NULL,
  opened_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_account PRIMARY KEY (account_id),
  CONSTRAINT uk_account_number UNIQUE (account_number),
  CONSTRAINT fk_account_customer FOREIGN KEY (customer_id)
    REFERENCES customer (customer_id) ON DELETE RESTRICT,
  CONSTRAINT ck_account_type CHECK (
    account_type IN ('CHECKING', 'SAVINGS', 'CREDIT')
  ),
  CONSTRAINT ck_account_status CHECK (
    status IN ('OPEN', 'CLOSED', 'FROZEN')
  )
);

-- Step 7 — ADDRESS
CREATE TABLE address (
  address_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id  BIGINT NOT NULL,
  address_type VARCHAR(20) NOT NULL,
  line1        VARCHAR(100) NOT NULL,
  line2        VARCHAR(100),
  city         VARCHAR(80) NOT NULL,
  region       VARCHAR(80),
  postal_code  VARCHAR(20),
  country_code CHAR(2) DEFAULT 'CA' NOT NULL,
  CONSTRAINT pk_address PRIMARY KEY (address_id),
  CONSTRAINT fk_address_customer FOREIGN KEY (customer_id)
    REFERENCES customer (customer_id) ON DELETE CASCADE,
  CONSTRAINT ck_address_type CHECK (
    address_type IN ('HOME', 'WORK', 'BILLING', 'OTHER')
  )
);

-- Step 8 — CUSTOMER_STATUS_HISTORY, append only
CREATE TABLE customer_status_history (
  history_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id    BIGINT NOT NULL,
  old_status     VARCHAR(20),
  new_status     VARCHAR(20) NOT NULL,
  changed_by     VARCHAR(100) NOT NULL,
  reason         VARCHAR(200),
  correlation_id VARCHAR(64),
  changed_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_cust_status_hist PRIMARY KEY (history_id),
  CONSTRAINT fk_hist_customer FOREIGN KEY (customer_id)
    REFERENCES customer (customer_id) ON DELETE CASCADE,
  CONSTRAINT ck_hist_new_status CHECK (
    new_status IN ('PROSPECT', 'ACTIVE', 'SUSPENDED', 'CLOSED')
  ),
  CONSTRAINT ck_hist_transition CHECK (old_status IS DISTINCT FROM new_status)
);

-- Step 9 — relationship and timeline indexes.
-- public_id and email_normalized already have unique indexes, no duplicates here.
CREATE INDEX ix_account_customer ON account (customer_id);
CREATE INDEX ix_address_customer ON address (customer_id);
CREATE INDEX ix_history_customer_time
  ON customer_status_history (customer_id, changed_at);
