apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE5EUTNOamN3SGhjTk1qWXdOekUxTVRnME5qQTNXaGNOTXpZd056RXlNVGcwTmpBMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE5EUTNOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVGZWWHRTQ3pRN2JaVjA1Z1cwQlF3enZKTlA4N1NqK3lBZEZVZmo3TUIKYklHNFJhSUtoWGNMb0d1Tks5M2JNMVl2bm5hUjFPMmxiOEQvWDhqVWxtL2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFoZmRXODZkR2I2bGdMYTJEeDRnCm9KZlRITGt3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU91SFZ1RDUyUVk1K1lEaGN6dldCNzhIRXlZbjFiWDQKdWc2ZGtkNVFEeDBpQWlBV3VDbjF6Z1oyS0tJUXBpZWRzbXJxNzBXQ2lZdkZkNGF6elRQemxMNHA4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.23.237.198:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: instructor01
    user: instructor01
  name: instructor01
current-context: instructor01
users:
- name: instructor01
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklOZVdYaTV5Q3lsc0d1RkVkQXlJal9JRlEtNWJKSExKa1Z5aTZIU2wzTjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpbnN0cnVjdG9yMDEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaW5zdHJ1Y3RvcjAxLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Imluc3RydWN0b3IwMS1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImEyYjQ1YTg4LTAwY2EtNGFlNS1iZGU5LTc5M2E0ZDI4MDM1NyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDppbnN0cnVjdG9yMDE6aW5zdHJ1Y3RvcjAxLXNhIn0.mstzE6aLn9K5r817_EVoRVzLjZ7a4Px7V5SBoLb2bVJXrESt9bO_L91EkoGVjIpl9Z7YLqUSPTcnEr7SCNP8p8-iZ5YQCloxpJsN0dP3vDDw1yMgIXnrV2zVxSH0ZTapFGe1SB1zhDKVZaHnSUEnsBhk0GPweJtR6n9vq1VCQ9RPt_CEX-sgsXdwXJETM1Ts71ATXfVb0A4dZTwn0RIwzvC4FQtIq90KIJquHQdjmQI_BRUNH8pPPtK_7i2GBsw8pqZJRMpbmFL-SaqJtXokw9HVJei03lBjzX17j2vKAug2DaEvGul6q2Jn8JJJgeubZHfYZD56IG-RRy4afP2a1A
