apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE5EUTNOamN3SGhjTk1qWXdOekUxTVRnME5qQTNXaGNOTXpZd056RXlNVGcwTmpBMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE5EUTNOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVGZWWHRTQ3pRN2JaVjA1Z1cwQlF3enZKTlA4N1NqK3lBZEZVZmo3TUIKYklHNFJhSUtoWGNMb0d1Tks5M2JNMVl2bm5hUjFPMmxiOEQvWDhqVWxtL2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFoZmRXODZkR2I2bGdMYTJEeDRnCm9KZlRITGt3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU91SFZ1RDUyUVk1K1lEaGN6dldCNzhIRXlZbjFiWDQKdWc2ZGtkNVFEeDBpQWlBV3VDbjF6Z1oyS0tJUXBpZWRzbXJxNzBXQ2lZdkZkNGF6elRQemxMNHA4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.23.237.198:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student15
    user: student15
  name: student15
current-context: student15
users:
- name: student15
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklOZVdYaTV5Q3lsc0d1RkVkQXlJal9JRlEtNWJKSExKa1Z5aTZIU2wzTjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MTUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDE1LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQxNS1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjJmOTQzMGYzLWE1MTgtNDYwNy1iMDE4LWNkMzU3Mjg3YjFlOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MTU6c3R1ZGVudDE1LXNhIn0.jQS_wwaEvgvhKP99VH_h7yYFO0Oa1jXUu_P-wa2eXoltNLy465VVBxgrg-ipEJv-gialFFF1qcYczy6H-_eo_BSRE3hRlqmO2bO5BabFgqOab9hzyW3d-MkLsMCIHTq76vEF42Gp2Oapio5ITDiw_LowJqejTNFqF1CD77hGMC8Gbt7O13dGZlXxxTIqnNfKLKEoG-Zm-s2nC6viOLvNoR_cZJKGOEZTlTMhGKVKsCXj_uxy2jgO5p2Gd1HEGxX7Cp4NdXrEKNxwxk-j5XGb0a5b4TJKk833XJ4JWuH6xMIGaxa1yCdcuSuKRlme5vHS0EZsiXnFgReSm7rVO52MWA
