apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE5EUTNOamN3SGhjTk1qWXdOekUxTVRnME5qQTNXaGNOTXpZd056RXlNVGcwTmpBMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE5EUTNOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVGZWWHRTQ3pRN2JaVjA1Z1cwQlF3enZKTlA4N1NqK3lBZEZVZmo3TUIKYklHNFJhSUtoWGNMb0d1Tks5M2JNMVl2bm5hUjFPMmxiOEQvWDhqVWxtL2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFoZmRXODZkR2I2bGdMYTJEeDRnCm9KZlRITGt3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU91SFZ1RDUyUVk1K1lEaGN6dldCNzhIRXlZbjFiWDQKdWc2ZGtkNVFEeDBpQWlBV3VDbjF6Z1oyS0tJUXBpZWRzbXJxNzBXQ2lZdkZkNGF6elRQemxMNHA4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.23.237.198:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student03
    user: student03
  name: student03
current-context: student03
users:
- name: student03
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklOZVdYaTV5Q3lsc0d1RkVkQXlJal9JRlEtNWJKSExKa1Z5aTZIU2wzTjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MDMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDAzLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQwMy1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjE5YzM0ZmJlLWVhZjItNGExMS04M2U2LTVlNDFiOTVhZTU5MiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MDM6c3R1ZGVudDAzLXNhIn0.1pyKlkvkIr-bC6Og0dohocUu_9CDRUl8P8ewgw-Y701XIij8zG5oNWTU0I3il4kRpZsdhvv_CNktZEnaxDG2Av7nQgQTs5t3EA_q1jxt4tCuuNPjdLs7m0zVPdEx_rAmao1op_Et02Qakut_4G5KpGEQKdLsCexPwqbgixOq9vBep2386U98wulzzDz8Co3Q7m75_LS03ZAfYnHgDvBSSPSvxLFx5J1_OD4TpK_T-E2gz50WAn8jK3N3seatIPaAq2bD0yLYtHpY_joz7IExFe6rrx8DX4Cwf5TrfMuZIHEmsyaLGcKgRyncaH-nTpDcAXnYKCcHt78ucxYACFA1cA
