apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE5EUTNOamN3SGhjTk1qWXdOekUxTVRnME5qQTNXaGNOTXpZd056RXlNVGcwTmpBMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE5EUTNOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVGZWWHRTQ3pRN2JaVjA1Z1cwQlF3enZKTlA4N1NqK3lBZEZVZmo3TUIKYklHNFJhSUtoWGNMb0d1Tks5M2JNMVl2bm5hUjFPMmxiOEQvWDhqVWxtL2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFoZmRXODZkR2I2bGdMYTJEeDRnCm9KZlRITGt3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU91SFZ1RDUyUVk1K1lEaGN6dldCNzhIRXlZbjFiWDQKdWc2ZGtkNVFEeDBpQWlBV3VDbjF6Z1oyS0tJUXBpZWRzbXJxNzBXQ2lZdkZkNGF6elRQemxMNHA4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.23.237.198:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student09
    user: student09
  name: student09
current-context: student09
users:
- name: student09
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklOZVdYaTV5Q3lsc0d1RkVkQXlJal9JRlEtNWJKSExKa1Z5aTZIU2wzTjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MDkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDA5LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQwOS1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImNlMGQ2MWUzLWE3MmQtNGU5My1iYzMwLWVmMjk4YzVmODU4YSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MDk6c3R1ZGVudDA5LXNhIn0.O42KnPdzyr9aZC4auIFz9YmQ4LD7Icn9OHeQGG7R2enM3Ip_b0t4gUwpmEA0WsnCFD6m6WvtN-_2IBfN-94rf_iskt7nN4FgUeFAglkImPUVNnxVIjJ42veWTiJqcX7Zx9_4vqoZ0scM1WiG81Tm6mZcY4grJjraDIkRW6FnFRmJ2zBKappb4aiYQTNnwnJBueUFILFjqmh-qXPJKlDQr8xYQn5eYNI65SlACFv4vh5tLxtW4SQQAHB1tvrh6xJ6q2mEeEbLHhfdlNKymygCYiYTUF2NX_FI_0gHKkbuNQ0Nl9FWbHc98xI2i00DGohrBk_wy9kJqe-uqlFZQJRdgA
