apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE5EUTNOamN3SGhjTk1qWXdOekUxTVRnME5qQTNXaGNOTXpZd056RXlNVGcwTmpBMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE5EUTNOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVGZWWHRTQ3pRN2JaVjA1Z1cwQlF3enZKTlA4N1NqK3lBZEZVZmo3TUIKYklHNFJhSUtoWGNMb0d1Tks5M2JNMVl2bm5hUjFPMmxiOEQvWDhqVWxtL2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFoZmRXODZkR2I2bGdMYTJEeDRnCm9KZlRITGt3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU91SFZ1RDUyUVk1K1lEaGN6dldCNzhIRXlZbjFiWDQKdWc2ZGtkNVFEeDBpQWlBV3VDbjF6Z1oyS0tJUXBpZWRzbXJxNzBXQ2lZdkZkNGF6elRQemxMNHA4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.23.237.198:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student14
    user: student14
  name: student14
current-context: student14
users:
- name: student14
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklOZVdYaTV5Q3lsc0d1RkVkQXlJal9JRlEtNWJKSExKa1Z5aTZIU2wzTjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MTQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDE0LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQxNC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjExMjE4ZmY0LWU0YTMtNDFiZS1iNTE1LThjYjRjNGU0MTExMCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MTQ6c3R1ZGVudDE0LXNhIn0.tZEsfED8DLtp30YcjABgJfUcwQiDgdXgPWZ7QSm1MXdyGmbVnltAsnQwOP6r4ywD1nTFlBXi0uiJfn1xpeXYORaeyQnKHnTrlcQ8O_A0O6-NDnwUEIU2_O1gbhf4m0cYyMH8SC3fykrua_Wm5L_DFcGQu_OUYs5CAp5T2L1SY0CBTiW_EiYI-ZJZiUyLLTZs2qCZ_IEDocT3u7opE2si0PaaWViJHG8JrFoTMSQ_jr1K7vzvFPwBSQkihgwXxttH3WWNdouBgbvaYbCy-IH-esiRDMA5PG-KmXHlp8U2j4n87oso1R41-IDKA2S2C7kakU9PR6aKewetgmFzeXfWvg
