apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE5EUTNOamN3SGhjTk1qWXdOekUxTVRnME5qQTNXaGNOTXpZd056RXlNVGcwTmpBMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE5EUTNOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVGZWWHRTQ3pRN2JaVjA1Z1cwQlF3enZKTlA4N1NqK3lBZEZVZmo3TUIKYklHNFJhSUtoWGNMb0d1Tks5M2JNMVl2bm5hUjFPMmxiOEQvWDhqVWxtL2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFoZmRXODZkR2I2bGdMYTJEeDRnCm9KZlRITGt3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU91SFZ1RDUyUVk1K1lEaGN6dldCNzhIRXlZbjFiWDQKdWc2ZGtkNVFEeDBpQWlBV3VDbjF6Z1oyS0tJUXBpZWRzbXJxNzBXQ2lZdkZkNGF6elRQemxMNHA4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.23.237.198:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student08
    user: student08
  name: student08
current-context: student08
users:
- name: student08
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklOZVdYaTV5Q3lsc0d1RkVkQXlJal9JRlEtNWJKSExKa1Z5aTZIU2wzTjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MDgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDA4LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQwOC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijc0MGVlYmMwLTVkM2MtNGE5ZS05NDdhLWRkNGI3MTlhYmY5NSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MDg6c3R1ZGVudDA4LXNhIn0.XhDbh0fG2WFg3NB1jlQH3FP-Ljx6bjEH7o4pWZyU-rqjHHlYZaSJ4-pfOhVZrJsqgj1Evq5Iqlk-NElup0-VpObn32WbNbGdnNMpAi0pthXf0LM2GWKqPGyiveo5y-MA1AtClgCGjvZsMkcyobrAiyGdl11ZOixGT2C3h5_g8kcPwwi8qRofGMBzVAR836lQObki2VEVHJHAfjimaJWLLcHEF4ehgCg8jT0JQ8HQidfeULIKag6BwWJkzxTO7gSKdo1U-Xpfayyt0RJ_ex1oDbphAoXcc_ykZ4_gLLk2_8gIKgQKEyOLOTOnfJvD9ciFQL9NODsJmBZc6FkXke7Fpg
