apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE1qazFOalF3SGhjTk1qWXdOekUxTVRRek1qUTBXaGNOTXpZd056RXlNVFF6TWpRMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE1qazFOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSOXRXWnQvd3hwazQ3MXNub0wwVG0vYmFzTm9QNk12OHRjUEZ6cTlLbkQKR1RRYnNiQnBKRUtIZDhmeG5xdTFYWGp0WmV5RXhyNlloODgzTGFwM29sTUtvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpMdDdkWEJ1cFQvSDN6WWlmVUtOCkNsMFREd0l3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVkxWazVLd1E0Uk5XbE02b2dOcmJ6bWxKWWdlL3VtYWkKQVgvOVk0SSsyd29DSVFEQncxUWNQL2JMbGxQZEpNL3NRbHkvNk5tT2VraWtFT252ajVKbEczRi9JUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.22.136.97:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student02
    user: student02
  name: student02
current-context: student02
users:
- name: student02
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImR4bDF0Y0MxOHV4eDZ1dzNabWdOV1c2RVlzMUF2VjdRS3dJb0ZIZ3hiODAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MDIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDAyLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQwMi1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImUxOGUwNTM5LTE1MjctNGU5MS04MWNlLWNhMzIxMTEzMDEyZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MDI6c3R1ZGVudDAyLXNhIn0.pPCSpE092-VpqNEXIk3oVq-hTGuoVS8iCgo_SrKRcXJ4KQUm-67GzcWYf9GhJUO-qqE9EP01I3B4fRPXKLvgJ-rF5TD4y-4sV33wzGTSfcr2Cu6apltFjo_jwdIIrMD7dk2SVm0rgNH_JGAHVj4PSqWnGfQnBtxDJ81Y2nJZMRos55sqHz0DmQgeJhpTr3fsrFb_aju_XyGQBep46_cfPtDYP9SNXbFCDNsFgSA56hHgvYBF4eXfkjRyMzznidXU0naO_4YxXD8ivUm0K91SV0VLbo2vjqRYCGm-UuZW2AxpYaIxmUydN94CtFzrE7gtdtAkbtin0j4qrbrv2b_4tg
