apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE1qazFOalF3SGhjTk1qWXdOekUxTVRRek1qUTBXaGNOTXpZd056RXlNVFF6TWpRMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE1qazFOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSOXRXWnQvd3hwazQ3MXNub0wwVG0vYmFzTm9QNk12OHRjUEZ6cTlLbkQKR1RRYnNiQnBKRUtIZDhmeG5xdTFYWGp0WmV5RXhyNlloODgzTGFwM29sTUtvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpMdDdkWEJ1cFQvSDN6WWlmVUtOCkNsMFREd0l3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVkxWazVLd1E0Uk5XbE02b2dOcmJ6bWxKWWdlL3VtYWkKQVgvOVk0SSsyd29DSVFEQncxUWNQL2JMbGxQZEpNL3NRbHkvNk5tT2VraWtFT252ajVKbEczRi9JUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.22.136.97:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student06
    user: student06
  name: student06
current-context: student06
users:
- name: student06
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImR4bDF0Y0MxOHV4eDZ1dzNabWdOV1c2RVlzMUF2VjdRS3dJb0ZIZ3hiODAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MDYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDA2LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQwNi1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjY2YmFkZmU3LWQ1YzYtNDZlOC04YzE3LTRiOTUzMzU3YTk2MCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MDY6c3R1ZGVudDA2LXNhIn0.qG6fm-wl8D5BWQWlWSB27wnn66ojm1nTVReYBytQ5mXLou_bd9vt-9d5RKQBDWKxE1D4ux-E2cICL1g-6KOaQRS-2M5oDrOkb6roOteR83sgtDhs20wq3IGxr6aU9sVt2qQHcx9VzANGh68wWfl368I0IbZsCJPZQ0sPb1c7QZnxasUNWK9IeZRUzgFglsFdh2gXlXX1uznRQyWKqIOqeC7OvmJVs0tEZdmXE4PzktuEQSAG7uVhdqt1ufLT7QhSWm7B7C4b-BgAqlWV2pbMfv_LZ6UwWRzLTx7xNwf5EPlDVe_IHjXF8_r8DJHAFeo8nXHBSDiWGsxQOx0gugIJyQ
