apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE1qazFOalF3SGhjTk1qWXdOekUxTVRRek1qUTBXaGNOTXpZd056RXlNVFF6TWpRMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE1qazFOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSOXRXWnQvd3hwazQ3MXNub0wwVG0vYmFzTm9QNk12OHRjUEZ6cTlLbkQKR1RRYnNiQnBKRUtIZDhmeG5xdTFYWGp0WmV5RXhyNlloODgzTGFwM29sTUtvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpMdDdkWEJ1cFQvSDN6WWlmVUtOCkNsMFREd0l3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVkxWazVLd1E0Uk5XbE02b2dOcmJ6bWxKWWdlL3VtYWkKQVgvOVk0SSsyd29DSVFEQncxUWNQL2JMbGxQZEpNL3NRbHkvNk5tT2VraWtFT252ajVKbEczRi9JUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.22.136.97:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student03
    user: student03
  name: student03
current-context: student03
users:
- name: student03
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImR4bDF0Y0MxOHV4eDZ1dzNabWdOV1c2RVlzMUF2VjdRS3dJb0ZIZ3hiODAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MDMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDAzLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQwMy1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjUwNDgxYmNmLTMwOWMtNGRlMy1iYTgzLWViMTk4NWFkYzBmNiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MDM6c3R1ZGVudDAzLXNhIn0.NKO7brbYgSBY4jbYepfqJmUCfoIuRwnjMXJHHey3Yo7BSKurGeyza6O35TyEJLgPzLjBuVCtntPbrmH-lBU9YZyfoLNjPS6fxxU_D_EfRRX-9K_5z3zFKZ1d3AaXb2x05_Gm7kj8FgNsIfKp44FmS2jXoR9CzuIOxFlJX9Xbo94DMq_uTJYlPblVtMt2HUGZ1KfLvK8THr-rGRzOJPpAV4iJnIFKj3MeoPCiKp2rHxQlvCdkyMM2MpzSRCmfDJ6Iq181TTkk3Xvv_3kBhj9LDXge-djnS9p92Cdfh2lyqPgxKm25Ux_ZCUaQUA3crtGh4lYxJMYo9PDR0AFrEx4iTw
