apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE1qazFOalF3SGhjTk1qWXdOekUxTVRRek1qUTBXaGNOTXpZd056RXlNVFF6TWpRMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE1qazFOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSOXRXWnQvd3hwazQ3MXNub0wwVG0vYmFzTm9QNk12OHRjUEZ6cTlLbkQKR1RRYnNiQnBKRUtIZDhmeG5xdTFYWGp0WmV5RXhyNlloODgzTGFwM29sTUtvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpMdDdkWEJ1cFQvSDN6WWlmVUtOCkNsMFREd0l3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVkxWazVLd1E0Uk5XbE02b2dOcmJ6bWxKWWdlL3VtYWkKQVgvOVk0SSsyd29DSVFEQncxUWNQL2JMbGxQZEpNL3NRbHkvNk5tT2VraWtFT252ajVKbEczRi9JUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.22.136.97:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student10
    user: student10
  name: student10
current-context: student10
users:
- name: student10
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImR4bDF0Y0MxOHV4eDZ1dzNabWdOV1c2RVlzMUF2VjdRS3dJb0ZIZ3hiODAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MTAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDEwLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQxMC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijk5NGI0OWNhLTkxMmItNDIzZi05ZGRkLTg3MGVhODQ3YjQ3MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MTA6c3R1ZGVudDEwLXNhIn0.eD4LMQADaDlY1Y_qKYN-tiIKgc1cgoyYxqIOlWckoHis2gb77CwDSDVDslrAONxUoNduloAx1FZ6dhZn31R2_cRW-mV--j0UxCnoqmemIZ6cXPw2hszxrHc11lupY3DJ6VdlOa9Ju4wBwUAMrYMJ5KY4uBh52Tvxk2sHHOt1S9yQQpbHvrBJSPPPU6GZb9iWS3Ac1_1KBs4YflqMUPVK0CA39MK_skpJbVC_dB2kKJBRm1eFF1iHO6qrT0xuPUcZ6y6sbQsYYZiNIpTfkNX86KrR0zX64_oBNMBAPTA5aiuXPcjGr_rPo7Q7qNXir2Itz1Of91V_D9TdNL7DuZJgjA
