apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE1qazFOalF3SGhjTk1qWXdOekUxTVRRek1qUTBXaGNOTXpZd056RXlNVFF6TWpRMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE1qazFOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSOXRXWnQvd3hwazQ3MXNub0wwVG0vYmFzTm9QNk12OHRjUEZ6cTlLbkQKR1RRYnNiQnBKRUtIZDhmeG5xdTFYWGp0WmV5RXhyNlloODgzTGFwM29sTUtvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpMdDdkWEJ1cFQvSDN6WWlmVUtOCkNsMFREd0l3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVkxWazVLd1E0Uk5XbE02b2dOcmJ6bWxKWWdlL3VtYWkKQVgvOVk0SSsyd29DSVFEQncxUWNQL2JMbGxQZEpNL3NRbHkvNk5tT2VraWtFT252ajVKbEczRi9JUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://100.22.136.97:6443
  name: bootcamp
contexts:
- context:
    cluster: bootcamp
    namespace: student07
    user: student07
  name: student07
current-context: student07
users:
- name: student07
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImR4bDF0Y0MxOHV4eDZ1dzNabWdOV1c2RVlzMUF2VjdRS3dJb0ZIZ3hiODAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50MDciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3R1ZGVudDA3LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0dWRlbnQwNy1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjkzYTY4M2QzLTFkOTItNDQ2Zi1iY2FmLWYyZjljNmRmNWJhMyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdHVkZW50MDc6c3R1ZGVudDA3LXNhIn0.XOkBxzNQ2TB4s30gCF-7E4ucJDGXZOlVmgFN2b1uYyNcRMvAFDER0iza_D25I-W0yy1M9vr8GJSSJCu_BKjED-l10h31ztaXqoWmq27k_VEoeFIY-BsPqQbcorAy17ADdjkadUrC7DgUESfAWrFegisElrHLQrJP78Y3ssfddC4nUSHjhQVX9h22hQBOOarUPgv9gLJRVSLysd4zJICt1nqJAqw0V4qgq41VUWi6eWyJyfC5fJGa-gR8UyEFu9YwQeuzCAsbFq7lARJXIdnwWyFJTDOiFh7zQgXiDrRLP1OTRKMhdaPjNfZvbCo2yVBLDDlPad9WfS3W2gx1_rf10A
