CREATE TABLE customer (
  customer_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id          VARCHAR(36)  NOT NULL,
  full_name          VARCHAR(200) NOT NULL,
  email   VARCHAR(320) NOT NULL,
  status             VARCHAR(32)  NOT NULL,
  created_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  version         BIGINT DEFAULT 0 NOT NULL,
  CONSTRAINT uk_customer_public_id UNIQUE (public_id),
  CONSTRAINT uk_customer_email_norm UNIQUE (email)
);

CREATE TABLE account (
  account_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   BIGINT NOT NULL,
  balance_cents BIGINT NOT NULL DEFAULT 0,
  status        VARCHAR(32) NOT NULL,
  CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
);

CREATE INDEX ix_account_customer ON account (customer_id);

--Lab 38 step 7, re-earned in the step 12 challenge cycle:
--ACTIVE list page 1,006 buffers -> 23, 10.57 ms -> 0.070 ms. The win is the ORDERING, not the
-- filter -- ACTIVE matches 70% of rows.
CREATE INDEX ix_customer_status_created
    ON customer (status, created_at DESC, customer_id DESC);